#!/bin/sh

set -e

family=`slimbookctl info | grep family | cut -d ":" -f 2`

if [ "$family" = "unknown" ]; then
    family="others"
fi

ln -sf "/boot/grub/themes/slimbook/images/$family.png" "/boot/grub/themes/slimbook/images/logo.png" 
